---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker

inputs:
  - name: mysql-concourse
  - name: tool-om

outputs:
  - name: json_file

run:
  path: mysql-concourse/ci/tasks/configure-json.sh

params:
  pcf_iaas:
  terraform_template:
