---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker

inputs:
  - name: mysql-concourse
  - name: tool-om

run:
  path: mysql-concourse/ci/tasks/deploy-mysql.sh

params:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:
